// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Repositories;

#nullable disable

namespace Portfolio.Repositories.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Common.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("FiberClients", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberInventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("QtyAfterTransaction")
                        .HasColumnType("numeric")
                        .HasColumnName("qty_after_transaction");

                    b.Property<decimal>("QtyBeforeTransaction")
                        .HasColumnType("numeric")
                        .HasColumnName("qty_before_transaction");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("FiberInventoryTransactions", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("QtyOnHand")
                        .HasColumnType("numeric")
                        .HasColumnName("qty_on_hand");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("numeric")
                        .HasColumnName("reorder_point");

                    b.Property<decimal>("ReorderQty")
                        .HasColumnType("numeric")
                        .HasColumnName("reorder_qty");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("warehouse_location");

                    b.HasKey("Id");

                    b.ToTable("FiberMaterials", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_sku");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ship_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("FiberOrders", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberShipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carrier_name");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_city");

                    b.Property<double>("DestinationLat")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_lat");

                    b.Property<double>("DestinationLng")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_lng");

                    b.Property<string>("DestinationState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_state");

                    b.Property<DateTime>("EstimatedArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_arrival");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<double>("OriginLat")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lat");

                    b.Property<double>("OriginLng")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lng");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ship_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FiberShipments", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcCondition")
                        .HasColumnType("integer");

                    b.Property<decimal>("AcreLot")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("AmenitiesScore")
                        .HasColumnType("integer");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<string>("BrokeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Redlands");

                    b.Property<int>("CommuteMin")
                        .HasColumnType("integer");

                    b.Property<int>("CrimeScore")
                        .HasColumnType("integer");

                    b.Property<int>("ElectricalCondition")
                        .HasColumnType("integer");

                    b.Property<int>("FloodRisk")
                        .HasColumnType("integer");

                    b.Property<int>("FloorPlanScore")
                        .HasColumnType("integer");

                    b.Property<int>("FutureAppreciation")
                        .HasColumnType("integer");

                    b.Property<decimal>("HoaFee")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("LastRenovation")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LotSqft")
                        .HasColumnType("integer");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PlumbingCondition")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("PropertyTax")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ResalePotential")
                        .HasColumnType("integer");

                    b.Property<int>("RoofCondition")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolRating")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("CA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TransitAccess")
                        .HasColumnType("integer");

                    b.Property<decimal>("Utilities")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Walkability")
                        .HasColumnType("integer");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Price");

                    b.HasIndex("City", "ZipCode");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.SavedFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserId", "LayerId", "FeatureId")
                        .IsUnique();

                    b.ToTable("SavedFeatures", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.SavedSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TopPropertyIds")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedSearches", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClaimType");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberInventoryTransaction", b =>
                {
                    b.HasOne("Portfolio.Common.Models.FiberMaterial", "Material")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberOrder", b =>
                {
                    b.HasOne("Portfolio.Common.Models.FiberClient", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberShipment", b =>
                {
                    b.HasOne("Portfolio.Common.Models.FiberOrder", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Portfolio.Common.Models.SavedFeature", b =>
                {
                    b.HasOne("Portfolio.Common.Models.Collection", "Collection")
                        .WithMany("SavedFeatures")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Portfolio.Common.Models.UserClaim", b =>
                {
                    b.HasOne("Portfolio.Common.Models.UserProfile", "UserProfile")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Portfolio.Common.Models.Collection", b =>
                {
                    b.Navigation("SavedFeatures");
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberClient", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberMaterial", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("Portfolio.Common.Models.FiberOrder", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Portfolio.Common.Models.UserProfile", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
